#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLNganHang")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTaiKhoan(TaiKhoan instance);
    partial void UpdateTaiKhoan(TaiKhoan instance);
    partial void DeleteTaiKhoan(TaiKhoan instance);
    partial void InsertKhachHangCaNhan(KhachHangCaNhan instance);
    partial void UpdateKhachHangCaNhan(KhachHangCaNhan instance);
    partial void DeleteKhachHangCaNhan(KhachHangCaNhan instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::DAL.Properties.Settings.Default.QLNganHangConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<KhachHangCaNhan> KhachHangCaNhans
		{
			get
			{
				return this.GetTable<KhachHangCaNhan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _IdTaiKhoan;
		
		private int _MaKhachHang;
		
		private string _LoaiTaiKhoan;
		
		private string _TenTaiKhoan;
		
		private string _TienTe;
		
		private string _TieuDeTK;
		
		private string _TieuDeNgan;
		
		private string _NhanVienLV;
		
		private string _PhiMa;
		
		private string _LoaiTK;
		
		private EntityRef<KhachHangCaNhan> _KhachHangCaNhan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdTaiKhoanChanging(long value);
    partial void OnIdTaiKhoanChanged();
    partial void OnMaKhachHangChanging(int value);
    partial void OnMaKhachHangChanged();
    partial void OnLoaiTaiKhoanChanging(string value);
    partial void OnLoaiTaiKhoanChanged();
    partial void OnTenTaiKhoanChanging(string value);
    partial void OnTenTaiKhoanChanged();
    partial void OnTienTeChanging(string value);
    partial void OnTienTeChanged();
    partial void OnTieuDeTKChanging(string value);
    partial void OnTieuDeTKChanged();
    partial void OnTieuDeNganChanging(string value);
    partial void OnTieuDeNganChanged();
    partial void OnNhanVienLVChanging(string value);
    partial void OnNhanVienLVChanged();
    partial void OnPhiMaChanging(string value);
    partial void OnPhiMaChanged();
    partial void OnLoaiTKChanging(string value);
    partial void OnLoaiTKChanged();
    #endregion
		
		public TaiKhoan()
		{
			this._KhachHangCaNhan = default(EntityRef<KhachHangCaNhan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTaiKhoan", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long IdTaiKhoan
		{
			get
			{
				return this._IdTaiKhoan;
			}
			set
			{
				if ((this._IdTaiKhoan != value))
				{
					this.OnIdTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._IdTaiKhoan = value;
					this.SendPropertyChanged("IdTaiKhoan");
					this.OnIdTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", DbType="Int NOT NULL")]
		public int MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					if (this._KhachHangCaNhan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiTaiKhoan", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string LoaiTaiKhoan
		{
			get
			{
				return this._LoaiTaiKhoan;
			}
			set
			{
				if ((this._LoaiTaiKhoan != value))
				{
					this.OnLoaiTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._LoaiTaiKhoan = value;
					this.SendPropertyChanged("LoaiTaiKhoan");
					this.OnLoaiTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTaiKhoan", DbType="NVarChar(255)")]
		public string TenTaiKhoan
		{
			get
			{
				return this._TenTaiKhoan;
			}
			set
			{
				if ((this._TenTaiKhoan != value))
				{
					this.OnTenTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TenTaiKhoan = value;
					this.SendPropertyChanged("TenTaiKhoan");
					this.OnTenTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienTe", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TienTe
		{
			get
			{
				return this._TienTe;
			}
			set
			{
				if ((this._TienTe != value))
				{
					this.OnTienTeChanging(value);
					this.SendPropertyChanging();
					this._TienTe = value;
					this.SendPropertyChanged("TienTe");
					this.OnTienTeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDeTK", DbType="NVarChar(255)")]
		public string TieuDeTK
		{
			get
			{
				return this._TieuDeTK;
			}
			set
			{
				if ((this._TieuDeTK != value))
				{
					this.OnTieuDeTKChanging(value);
					this.SendPropertyChanging();
					this._TieuDeTK = value;
					this.SendPropertyChanged("TieuDeTK");
					this.OnTieuDeTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDeNgan", DbType="NVarChar(50)")]
		public string TieuDeNgan
		{
			get
			{
				return this._TieuDeNgan;
			}
			set
			{
				if ((this._TieuDeNgan != value))
				{
					this.OnTieuDeNganChanging(value);
					this.SendPropertyChanging();
					this._TieuDeNgan = value;
					this.SendPropertyChanged("TieuDeNgan");
					this.OnTieuDeNganChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhanVienLV", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NhanVienLV
		{
			get
			{
				return this._NhanVienLV;
			}
			set
			{
				if ((this._NhanVienLV != value))
				{
					this.OnNhanVienLVChanging(value);
					this.SendPropertyChanging();
					this._NhanVienLV = value;
					this.SendPropertyChanged("NhanVienLV");
					this.OnNhanVienLVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhiMa", DbType="NVarChar(255)")]
		public string PhiMa
		{
			get
			{
				return this._PhiMa;
			}
			set
			{
				if ((this._PhiMa != value))
				{
					this.OnPhiMaChanging(value);
					this.SendPropertyChanging();
					this._PhiMa = value;
					this.SendPropertyChanged("PhiMa");
					this.OnPhiMaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiTK", DbType="NVarChar(255)")]
		public string LoaiTK
		{
			get
			{
				return this._LoaiTK;
			}
			set
			{
				if ((this._LoaiTK != value))
				{
					this.OnLoaiTKChanging(value);
					this.SendPropertyChanging();
					this._LoaiTK = value;
					this.SendPropertyChanged("LoaiTK");
					this.OnLoaiTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHangCaNhan_TaiKhoan", Storage="_KhachHangCaNhan", ThisKey="MaKhachHang", OtherKey="IdKhachHangCN", IsForeignKey=true)]
		public KhachHangCaNhan KhachHangCaNhan
		{
			get
			{
				return this._KhachHangCaNhan.Entity;
			}
			set
			{
				KhachHangCaNhan previousValue = this._KhachHangCaNhan.Entity;
				if (((previousValue != value) 
							|| (this._KhachHangCaNhan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHangCaNhan.Entity = null;
						previousValue.TaiKhoans.Remove(this);
					}
					this._KhachHangCaNhan.Entity = value;
					if ((value != null))
					{
						value.TaiKhoans.Add(this);
						this._MaKhachHang = value.IdKhachHangCN;
					}
					else
					{
						this._MaKhachHang = default(int);
					}
					this.SendPropertyChanged("KhachHangCaNhan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHangCaNhan")]
	public partial class KhachHangCaNhan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdKhachHangCN;
		
		private string _TenKhachHang;
		
		private System.DateTime _NgaySinh;
		
		private string _DiaChi;
		
		private string _SoDienThoai;
		
		private string _QuocGia;
		
		private string _QuocTich;
		
		private string _LoaiGiayTo;
		
		private string _SoGiayTo;
		
		private System.DateTime _NgayCap;
		
		private System.Nullable<System.DateTime> _NgayHetHan;
		
		private string _NoiCap;
		
		private string _Email;
		
		private int _NganhChinh;
		
		private int _Nganh;
		
		private string _NhanVienLV;
		
		private EntitySet<TaiKhoan> _TaiKhoans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdKhachHangCNChanging(int value);
    partial void OnIdKhachHangCNChanged();
    partial void OnTenKhachHangChanging(string value);
    partial void OnTenKhachHangChanged();
    partial void OnNgaySinhChanging(System.DateTime value);
    partial void OnNgaySinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnQuocGiaChanging(string value);
    partial void OnQuocGiaChanged();
    partial void OnQuocTichChanging(string value);
    partial void OnQuocTichChanged();
    partial void OnLoaiGiayToChanging(string value);
    partial void OnLoaiGiayToChanged();
    partial void OnSoGiayToChanging(string value);
    partial void OnSoGiayToChanged();
    partial void OnNgayCapChanging(System.DateTime value);
    partial void OnNgayCapChanged();
    partial void OnNgayHetHanChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayHetHanChanged();
    partial void OnNoiCapChanging(string value);
    partial void OnNoiCapChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnNganhChinhChanging(int value);
    partial void OnNganhChinhChanged();
    partial void OnNganhChanging(int value);
    partial void OnNganhChanged();
    partial void OnNhanVienLVChanging(string value);
    partial void OnNhanVienLVChanged();
    #endregion
		
		public KhachHangCaNhan()
		{
			this._TaiKhoans = new EntitySet<TaiKhoan>(new Action<TaiKhoan>(this.attach_TaiKhoans), new Action<TaiKhoan>(this.detach_TaiKhoans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdKhachHangCN", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdKhachHangCN
		{
			get
			{
				return this._IdKhachHangCN;
			}
			set
			{
				if ((this._IdKhachHangCN != value))
				{
					this.OnIdKhachHangCNChanging(value);
					this.SendPropertyChanging();
					this._IdKhachHangCN = value;
					this.SendPropertyChanged("IdKhachHangCN");
					this.OnIdKhachHangCNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhachHang", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenKhachHang
		{
			get
			{
				return this._TenKhachHang;
			}
			set
			{
				if ((this._TenKhachHang != value))
				{
					this.OnTenKhachHangChanging(value);
					this.SendPropertyChanging();
					this._TenKhachHang = value;
					this.SendPropertyChanged("TenKhachHang");
					this.OnTenKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime NOT NULL")]
		public System.DateTime NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="Char(11) NOT NULL", CanBeNull=false)]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuocGia", DbType="NVarChar(50)")]
		public string QuocGia
		{
			get
			{
				return this._QuocGia;
			}
			set
			{
				if ((this._QuocGia != value))
				{
					this.OnQuocGiaChanging(value);
					this.SendPropertyChanging();
					this._QuocGia = value;
					this.SendPropertyChanged("QuocGia");
					this.OnQuocGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuocTich", DbType="NVarChar(50)")]
		public string QuocTich
		{
			get
			{
				return this._QuocTich;
			}
			set
			{
				if ((this._QuocTich != value))
				{
					this.OnQuocTichChanging(value);
					this.SendPropertyChanging();
					this._QuocTich = value;
					this.SendPropertyChanged("QuocTich");
					this.OnQuocTichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiGiayTo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LoaiGiayTo
		{
			get
			{
				return this._LoaiGiayTo;
			}
			set
			{
				if ((this._LoaiGiayTo != value))
				{
					this.OnLoaiGiayToChanging(value);
					this.SendPropertyChanging();
					this._LoaiGiayTo = value;
					this.SendPropertyChanged("LoaiGiayTo");
					this.OnLoaiGiayToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoGiayTo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SoGiayTo
		{
			get
			{
				return this._SoGiayTo;
			}
			set
			{
				if ((this._SoGiayTo != value))
				{
					this.OnSoGiayToChanging(value);
					this.SendPropertyChanging();
					this._SoGiayTo = value;
					this.SendPropertyChanged("SoGiayTo");
					this.OnSoGiayToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCap", DbType="DateTime NOT NULL")]
		public System.DateTime NgayCap
		{
			get
			{
				return this._NgayCap;
			}
			set
			{
				if ((this._NgayCap != value))
				{
					this.OnNgayCapChanging(value);
					this.SendPropertyChanging();
					this._NgayCap = value;
					this.SendPropertyChanged("NgayCap");
					this.OnNgayCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayHetHan", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayHetHan
		{
			get
			{
				return this._NgayHetHan;
			}
			set
			{
				if ((this._NgayHetHan != value))
				{
					this.OnNgayHetHanChanging(value);
					this.SendPropertyChanging();
					this._NgayHetHan = value;
					this.SendPropertyChanged("NgayHetHan");
					this.OnNgayHetHanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiCap", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string NoiCap
		{
			get
			{
				return this._NoiCap;
			}
			set
			{
				if ((this._NoiCap != value))
				{
					this.OnNoiCapChanging(value);
					this.SendPropertyChanging();
					this._NoiCap = value;
					this.SendPropertyChanged("NoiCap");
					this.OnNoiCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(255)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NganhChinh", DbType="Int NOT NULL")]
		public int NganhChinh
		{
			get
			{
				return this._NganhChinh;
			}
			set
			{
				if ((this._NganhChinh != value))
				{
					this.OnNganhChinhChanging(value);
					this.SendPropertyChanging();
					this._NganhChinh = value;
					this.SendPropertyChanged("NganhChinh");
					this.OnNganhChinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nganh", DbType="Int NOT NULL")]
		public int Nganh
		{
			get
			{
				return this._Nganh;
			}
			set
			{
				if ((this._Nganh != value))
				{
					this.OnNganhChanging(value);
					this.SendPropertyChanging();
					this._Nganh = value;
					this.SendPropertyChanged("Nganh");
					this.OnNganhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhanVienLV", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NhanVienLV
		{
			get
			{
				return this._NhanVienLV;
			}
			set
			{
				if ((this._NhanVienLV != value))
				{
					this.OnNhanVienLVChanging(value);
					this.SendPropertyChanging();
					this._NhanVienLV = value;
					this.SendPropertyChanged("NhanVienLV");
					this.OnNhanVienLVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHangCaNhan_TaiKhoan", Storage="_TaiKhoans", ThisKey="IdKhachHangCN", OtherKey="MaKhachHang")]
		public EntitySet<TaiKhoan> TaiKhoans
		{
			get
			{
				return this._TaiKhoans;
			}
			set
			{
				this._TaiKhoans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TaiKhoans(TaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.KhachHangCaNhan = this;
		}
		
		private void detach_TaiKhoans(TaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.KhachHangCaNhan = null;
		}
	}
}
#pragma warning restore 1591
