#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLNganHang")]
	public partial class QLNganHangDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDangNhap(DangNhap instance);
    partial void UpdateDangNhap(DangNhap instance);
    partial void DeleteDangNhap(DangNhap instance);
    partial void InsertChiTietGD(ChiTietGD instance);
    partial void UpdateChiTietGD(ChiTietGD instance);
    partial void DeleteChiTietGD(ChiTietGD instance);
    partial void InsertKhachHangCaNhan(KhachHangCaNhan instance);
    partial void UpdateKhachHangCaNhan(KhachHangCaNhan instance);
    partial void DeleteKhachHangCaNhan(KhachHangCaNhan instance);
    partial void InsertNganh(Nganh instance);
    partial void UpdateNganh(Nganh instance);
    partial void DeleteNganh(Nganh instance);
    partial void InsertNganhChinh(NganhChinh instance);
    partial void UpdateNganhChinh(NganhChinh instance);
    partial void DeleteNganhChinh(NganhChinh instance);
    partial void InsertSoDuTinDung(SoDuTinDung instance);
    partial void UpdateSoDuTinDung(SoDuTinDung instance);
    partial void DeleteSoDuTinDung(SoDuTinDung instance);
    partial void InsertTaiKhoan(TaiKhoan instance);
    partial void UpdateTaiKhoan(TaiKhoan instance);
    partial void DeleteTaiKhoan(TaiKhoan instance);
    #endregion
		
		public QLNganHangDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLNganHangDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLNganHangDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLNganHangDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DangNhap> DangNhaps
		{
			get
			{
				return this.GetTable<DangNhap>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietGD> ChiTietGDs
		{
			get
			{
				return this.GetTable<ChiTietGD>();
			}
		}
		
		public System.Data.Linq.Table<KhachHangCaNhan> KhachHangCaNhans
		{
			get
			{
				return this.GetTable<KhachHangCaNhan>();
			}
		}
		
		public System.Data.Linq.Table<Nganh> Nganhs
		{
			get
			{
				return this.GetTable<Nganh>();
			}
		}
		
		public System.Data.Linq.Table<NganhChinh> NganhChinhs
		{
			get
			{
				return this.GetTable<NganhChinh>();
			}
		}
		
		public System.Data.Linq.Table<SoDuTinDung> SoDuTinDungs
		{
			get
			{
				return this.GetTable<SoDuTinDung>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DangNhap")]
	public partial class DangNhap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TenDangNhap;
		
		private string _MatKhau;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    #endregion
		
		public DangNhap()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietGD")]
	public partial class ChiTietGD : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _MaGD;
		
		private long _SoTKNguoiChuyen;
		
		private long _SoTKNguoiNhan;
		
		private double _SoTien;
		
		private System.DateTime _NgayGio;
		
		private string _DienGia;
		
		private EntityRef<TaiKhoan> _TaiKhoan;
		
		private EntityRef<TaiKhoan> _TaiKhoan1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGDChanging(long value);
    partial void OnMaGDChanged();
    partial void OnSoTKNguoiChuyenChanging(long value);
    partial void OnSoTKNguoiChuyenChanged();
    partial void OnSoTKNguoiNhanChanging(long value);
    partial void OnSoTKNguoiNhanChanged();
    partial void OnSoTienChanging(double value);
    partial void OnSoTienChanged();
    partial void OnNgayGioChanging(System.DateTime value);
    partial void OnNgayGioChanged();
    partial void OnDienGiaChanging(string value);
    partial void OnDienGiaChanged();
    #endregion
		
		public ChiTietGD()
		{
			this._TaiKhoan = default(EntityRef<TaiKhoan>);
			this._TaiKhoan1 = default(EntityRef<TaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGD", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long MaGD
		{
			get
			{
				return this._MaGD;
			}
			set
			{
				if ((this._MaGD != value))
				{
					this.OnMaGDChanging(value);
					this.SendPropertyChanging();
					this._MaGD = value;
					this.SendPropertyChanged("MaGD");
					this.OnMaGDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTKNguoiChuyen", DbType="BigInt NOT NULL")]
		public long SoTKNguoiChuyen
		{
			get
			{
				return this._SoTKNguoiChuyen;
			}
			set
			{
				if ((this._SoTKNguoiChuyen != value))
				{
					if (this._TaiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSoTKNguoiChuyenChanging(value);
					this.SendPropertyChanging();
					this._SoTKNguoiChuyen = value;
					this.SendPropertyChanged("SoTKNguoiChuyen");
					this.OnSoTKNguoiChuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTKNguoiNhan", DbType="BigInt NOT NULL")]
		public long SoTKNguoiNhan
		{
			get
			{
				return this._SoTKNguoiNhan;
			}
			set
			{
				if ((this._SoTKNguoiNhan != value))
				{
					if (this._TaiKhoan1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSoTKNguoiNhanChanging(value);
					this.SendPropertyChanging();
					this._SoTKNguoiNhan = value;
					this.SendPropertyChanged("SoTKNguoiNhan");
					this.OnSoTKNguoiNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTien", DbType="Float NOT NULL")]
		public double SoTien
		{
			get
			{
				return this._SoTien;
			}
			set
			{
				if ((this._SoTien != value))
				{
					this.OnSoTienChanging(value);
					this.SendPropertyChanging();
					this._SoTien = value;
					this.SendPropertyChanged("SoTien");
					this.OnSoTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayGio", DbType="DateTime NOT NULL")]
		public System.DateTime NgayGio
		{
			get
			{
				return this._NgayGio;
			}
			set
			{
				if ((this._NgayGio != value))
				{
					this.OnNgayGioChanging(value);
					this.SendPropertyChanging();
					this._NgayGio = value;
					this.SendPropertyChanged("NgayGio");
					this.OnNgayGioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienGia", DbType="NVarChar(300) NOT NULL", CanBeNull=false)]
		public string DienGia
		{
			get
			{
				return this._DienGia;
			}
			set
			{
				if ((this._DienGia != value))
				{
					this.OnDienGiaChanging(value);
					this.SendPropertyChanging();
					this._DienGia = value;
					this.SendPropertyChanged("DienGia");
					this.OnDienGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_ChiTietGD", Storage="_TaiKhoan", ThisKey="SoTKNguoiChuyen", OtherKey="IdTaiKhoan", IsForeignKey=true)]
		public TaiKhoan TaiKhoan
		{
			get
			{
				return this._TaiKhoan.Entity;
			}
			set
			{
				TaiKhoan previousValue = this._TaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._TaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TaiKhoan.Entity = null;
						previousValue.ChiTietGDs.Remove(this);
					}
					this._TaiKhoan.Entity = value;
					if ((value != null))
					{
						value.ChiTietGDs.Add(this);
						this._SoTKNguoiChuyen = value.IdTaiKhoan;
					}
					else
					{
						this._SoTKNguoiChuyen = default(long);
					}
					this.SendPropertyChanged("TaiKhoan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_ChiTietGD1", Storage="_TaiKhoan1", ThisKey="SoTKNguoiNhan", OtherKey="IdTaiKhoan", IsForeignKey=true)]
		public TaiKhoan TaiKhoan1
		{
			get
			{
				return this._TaiKhoan1.Entity;
			}
			set
			{
				TaiKhoan previousValue = this._TaiKhoan1.Entity;
				if (((previousValue != value) 
							|| (this._TaiKhoan1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TaiKhoan1.Entity = null;
						previousValue.ChiTietGDs1.Remove(this);
					}
					this._TaiKhoan1.Entity = value;
					if ((value != null))
					{
						value.ChiTietGDs1.Add(this);
						this._SoTKNguoiNhan = value.IdTaiKhoan;
					}
					else
					{
						this._SoTKNguoiNhan = default(long);
					}
					this.SendPropertyChanged("TaiKhoan1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHangCaNhan")]
	public partial class KhachHangCaNhan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdKhachHangCN;
		
		private string _TenKhachHang;
		
		private System.Data.Linq.Binary _Avarta;
		
		private System.DateTime _NgaySinh;
		
		private string _DiaChi;
		
		private string _SoDienThoai;
		
		private string _QuocGia;
		
		private string _QuocTich;
		
		private string _LoaiGiayTo;
		
		private string _SoGiayTo;
		
		private System.DateTime _NgayCap;
		
		private System.Nullable<System.DateTime> _NgayHetHan;
		
		private string _NoiCap;
		
		private string _Email;
		
		private int _NganhChinh;
		
		private int _IdNganh;
		
		private string _NhanVienLV;
		
		private EntitySet<TaiKhoan> _TaiKhoans;
		
		private EntityRef<Nganh> _Nganh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdKhachHangCNChanging(int value);
    partial void OnIdKhachHangCNChanged();
    partial void OnTenKhachHangChanging(string value);
    partial void OnTenKhachHangChanged();
    partial void OnAvartaChanging(System.Data.Linq.Binary value);
    partial void OnAvartaChanged();
    partial void OnNgaySinhChanging(System.DateTime value);
    partial void OnNgaySinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnQuocGiaChanging(string value);
    partial void OnQuocGiaChanged();
    partial void OnQuocTichChanging(string value);
    partial void OnQuocTichChanged();
    partial void OnLoaiGiayToChanging(string value);
    partial void OnLoaiGiayToChanged();
    partial void OnSoGiayToChanging(string value);
    partial void OnSoGiayToChanged();
    partial void OnNgayCapChanging(System.DateTime value);
    partial void OnNgayCapChanged();
    partial void OnNgayHetHanChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayHetHanChanged();
    partial void OnNoiCapChanging(string value);
    partial void OnNoiCapChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnNganhChinhChanging(int value);
    partial void OnNganhChinhChanged();
    partial void OnIdNganhChanging(int value);
    partial void OnIdNganhChanged();
    partial void OnNhanVienLVChanging(string value);
    partial void OnNhanVienLVChanged();
    #endregion
		
		public KhachHangCaNhan()
		{
			this._TaiKhoans = new EntitySet<TaiKhoan>(new Action<TaiKhoan>(this.attach_TaiKhoans), new Action<TaiKhoan>(this.detach_TaiKhoans));
			this._Nganh = default(EntityRef<Nganh>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdKhachHangCN", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdKhachHangCN
		{
			get
			{
				return this._IdKhachHangCN;
			}
			set
			{
				if ((this._IdKhachHangCN != value))
				{
					this.OnIdKhachHangCNChanging(value);
					this.SendPropertyChanging();
					this._IdKhachHangCN = value;
					this.SendPropertyChanged("IdKhachHangCN");
					this.OnIdKhachHangCNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhachHang", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenKhachHang
		{
			get
			{
				return this._TenKhachHang;
			}
			set
			{
				if ((this._TenKhachHang != value))
				{
					this.OnTenKhachHangChanging(value);
					this.SendPropertyChanging();
					this._TenKhachHang = value;
					this.SendPropertyChanged("TenKhachHang");
					this.OnTenKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Avarta", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Avarta
		{
			get
			{
				return this._Avarta;
			}
			set
			{
				if ((this._Avarta != value))
				{
					this.OnAvartaChanging(value);
					this.SendPropertyChanging();
					this._Avarta = value;
					this.SendPropertyChanged("Avarta");
					this.OnAvartaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime NOT NULL")]
		public System.DateTime NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="Char(11) NOT NULL", CanBeNull=false)]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuocGia", DbType="NVarChar(50)")]
		public string QuocGia
		{
			get
			{
				return this._QuocGia;
			}
			set
			{
				if ((this._QuocGia != value))
				{
					this.OnQuocGiaChanging(value);
					this.SendPropertyChanging();
					this._QuocGia = value;
					this.SendPropertyChanged("QuocGia");
					this.OnQuocGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuocTich", DbType="NVarChar(50)")]
		public string QuocTich
		{
			get
			{
				return this._QuocTich;
			}
			set
			{
				if ((this._QuocTich != value))
				{
					this.OnQuocTichChanging(value);
					this.SendPropertyChanging();
					this._QuocTich = value;
					this.SendPropertyChanged("QuocTich");
					this.OnQuocTichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiGiayTo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LoaiGiayTo
		{
			get
			{
				return this._LoaiGiayTo;
			}
			set
			{
				if ((this._LoaiGiayTo != value))
				{
					this.OnLoaiGiayToChanging(value);
					this.SendPropertyChanging();
					this._LoaiGiayTo = value;
					this.SendPropertyChanged("LoaiGiayTo");
					this.OnLoaiGiayToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoGiayTo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SoGiayTo
		{
			get
			{
				return this._SoGiayTo;
			}
			set
			{
				if ((this._SoGiayTo != value))
				{
					this.OnSoGiayToChanging(value);
					this.SendPropertyChanging();
					this._SoGiayTo = value;
					this.SendPropertyChanged("SoGiayTo");
					this.OnSoGiayToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCap", DbType="DateTime NOT NULL")]
		public System.DateTime NgayCap
		{
			get
			{
				return this._NgayCap;
			}
			set
			{
				if ((this._NgayCap != value))
				{
					this.OnNgayCapChanging(value);
					this.SendPropertyChanging();
					this._NgayCap = value;
					this.SendPropertyChanged("NgayCap");
					this.OnNgayCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayHetHan", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayHetHan
		{
			get
			{
				return this._NgayHetHan;
			}
			set
			{
				if ((this._NgayHetHan != value))
				{
					this.OnNgayHetHanChanging(value);
					this.SendPropertyChanging();
					this._NgayHetHan = value;
					this.SendPropertyChanged("NgayHetHan");
					this.OnNgayHetHanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiCap", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string NoiCap
		{
			get
			{
				return this._NoiCap;
			}
			set
			{
				if ((this._NoiCap != value))
				{
					this.OnNoiCapChanging(value);
					this.SendPropertyChanging();
					this._NoiCap = value;
					this.SendPropertyChanged("NoiCap");
					this.OnNoiCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(255)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NganhChinh", DbType="Int NOT NULL")]
		public int NganhChinh
		{
			get
			{
				return this._NganhChinh;
			}
			set
			{
				if ((this._NganhChinh != value))
				{
					this.OnNganhChinhChanging(value);
					this.SendPropertyChanging();
					this._NganhChinh = value;
					this.SendPropertyChanged("NganhChinh");
					this.OnNganhChinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdNganh", DbType="Int NOT NULL")]
		public int IdNganh
		{
			get
			{
				return this._IdNganh;
			}
			set
			{
				if ((this._IdNganh != value))
				{
					if (this._Nganh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdNganhChanging(value);
					this.SendPropertyChanging();
					this._IdNganh = value;
					this.SendPropertyChanged("IdNganh");
					this.OnIdNganhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhanVienLV", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NhanVienLV
		{
			get
			{
				return this._NhanVienLV;
			}
			set
			{
				if ((this._NhanVienLV != value))
				{
					this.OnNhanVienLVChanging(value);
					this.SendPropertyChanging();
					this._NhanVienLV = value;
					this.SendPropertyChanged("NhanVienLV");
					this.OnNhanVienLVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHangCaNhan_TaiKhoan", Storage="_TaiKhoans", ThisKey="IdKhachHangCN", OtherKey="MaKhachHang")]
		public EntitySet<TaiKhoan> TaiKhoans
		{
			get
			{
				return this._TaiKhoans;
			}
			set
			{
				this._TaiKhoans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nganh_KhachHangCaNhan", Storage="_Nganh", ThisKey="IdNganh", OtherKey="IdNganh", IsForeignKey=true)]
		public Nganh Nganh
		{
			get
			{
				return this._Nganh.Entity;
			}
			set
			{
				Nganh previousValue = this._Nganh.Entity;
				if (((previousValue != value) 
							|| (this._Nganh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Nganh.Entity = null;
						previousValue.KhachHangCaNhans.Remove(this);
					}
					this._Nganh.Entity = value;
					if ((value != null))
					{
						value.KhachHangCaNhans.Add(this);
						this._IdNganh = value.IdNganh;
					}
					else
					{
						this._IdNganh = default(int);
					}
					this.SendPropertyChanged("Nganh");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TaiKhoans(TaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.KhachHangCaNhan = this;
		}
		
		private void detach_TaiKhoans(TaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.KhachHangCaNhan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Nganh")]
	public partial class Nganh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdNganh;
		
		private string _TenNganh;
		
		private System.Nullable<int> _IdNganhChinh;
		
		private EntitySet<KhachHangCaNhan> _KhachHangCaNhans;
		
		private EntityRef<NganhChinh> _NganhChinh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdNganhChanging(int value);
    partial void OnIdNganhChanged();
    partial void OnTenNganhChanging(string value);
    partial void OnTenNganhChanged();
    partial void OnIdNganhChinhChanging(System.Nullable<int> value);
    partial void OnIdNganhChinhChanged();
    #endregion
		
		public Nganh()
		{
			this._KhachHangCaNhans = new EntitySet<KhachHangCaNhan>(new Action<KhachHangCaNhan>(this.attach_KhachHangCaNhans), new Action<KhachHangCaNhan>(this.detach_KhachHangCaNhans));
			this._NganhChinh = default(EntityRef<NganhChinh>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdNganh", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdNganh
		{
			get
			{
				return this._IdNganh;
			}
			set
			{
				if ((this._IdNganh != value))
				{
					this.OnIdNganhChanging(value);
					this.SendPropertyChanging();
					this._IdNganh = value;
					this.SendPropertyChanged("IdNganh");
					this.OnIdNganhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNganh", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string TenNganh
		{
			get
			{
				return this._TenNganh;
			}
			set
			{
				if ((this._TenNganh != value))
				{
					this.OnTenNganhChanging(value);
					this.SendPropertyChanging();
					this._TenNganh = value;
					this.SendPropertyChanged("TenNganh");
					this.OnTenNganhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdNganhChinh", DbType="Int")]
		public System.Nullable<int> IdNganhChinh
		{
			get
			{
				return this._IdNganhChinh;
			}
			set
			{
				if ((this._IdNganhChinh != value))
				{
					if (this._NganhChinh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdNganhChinhChanging(value);
					this.SendPropertyChanging();
					this._IdNganhChinh = value;
					this.SendPropertyChanged("IdNganhChinh");
					this.OnIdNganhChinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nganh_KhachHangCaNhan", Storage="_KhachHangCaNhans", ThisKey="IdNganh", OtherKey="IdNganh")]
		public EntitySet<KhachHangCaNhan> KhachHangCaNhans
		{
			get
			{
				return this._KhachHangCaNhans;
			}
			set
			{
				this._KhachHangCaNhans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NganhChinh_Nganh", Storage="_NganhChinh", ThisKey="IdNganhChinh", OtherKey="IdNganhChinh", IsForeignKey=true)]
		public NganhChinh NganhChinh
		{
			get
			{
				return this._NganhChinh.Entity;
			}
			set
			{
				NganhChinh previousValue = this._NganhChinh.Entity;
				if (((previousValue != value) 
							|| (this._NganhChinh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NganhChinh.Entity = null;
						previousValue.Nganhs.Remove(this);
					}
					this._NganhChinh.Entity = value;
					if ((value != null))
					{
						value.Nganhs.Add(this);
						this._IdNganhChinh = value.IdNganhChinh;
					}
					else
					{
						this._IdNganhChinh = default(Nullable<int>);
					}
					this.SendPropertyChanged("NganhChinh");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KhachHangCaNhans(KhachHangCaNhan entity)
		{
			this.SendPropertyChanging();
			entity.Nganh = this;
		}
		
		private void detach_KhachHangCaNhans(KhachHangCaNhan entity)
		{
			this.SendPropertyChanging();
			entity.Nganh = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NganhChinh")]
	public partial class NganhChinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdNganhChinh;
		
		private string _TenNganh;
		
		private EntitySet<Nganh> _Nganhs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdNganhChinhChanging(int value);
    partial void OnIdNganhChinhChanged();
    partial void OnTenNganhChanging(string value);
    partial void OnTenNganhChanged();
    #endregion
		
		public NganhChinh()
		{
			this._Nganhs = new EntitySet<Nganh>(new Action<Nganh>(this.attach_Nganhs), new Action<Nganh>(this.detach_Nganhs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdNganhChinh", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdNganhChinh
		{
			get
			{
				return this._IdNganhChinh;
			}
			set
			{
				if ((this._IdNganhChinh != value))
				{
					this.OnIdNganhChinhChanging(value);
					this.SendPropertyChanging();
					this._IdNganhChinh = value;
					this.SendPropertyChanged("IdNganhChinh");
					this.OnIdNganhChinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNganh", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string TenNganh
		{
			get
			{
				return this._TenNganh;
			}
			set
			{
				if ((this._TenNganh != value))
				{
					this.OnTenNganhChanging(value);
					this.SendPropertyChanging();
					this._TenNganh = value;
					this.SendPropertyChanged("TenNganh");
					this.OnTenNganhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NganhChinh_Nganh", Storage="_Nganhs", ThisKey="IdNganhChinh", OtherKey="IdNganhChinh")]
		public EntitySet<Nganh> Nganhs
		{
			get
			{
				return this._Nganhs;
			}
			set
			{
				this._Nganhs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Nganhs(Nganh entity)
		{
			this.SendPropertyChanging();
			entity.NganhChinh = this;
		}
		
		private void detach_Nganhs(Nganh entity)
		{
			this.SendPropertyChanging();
			entity.NganhChinh = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SoDuTinDung")]
	public partial class SoDuTinDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _IdTaiKhoan;
		
		private System.Nullable<double> _SoDuTK;
		
		private EntityRef<TaiKhoan> _TaiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdTaiKhoanChanging(long value);
    partial void OnIdTaiKhoanChanged();
    partial void OnSoDuTKChanging(System.Nullable<double> value);
    partial void OnSoDuTKChanged();
    #endregion
		
		public SoDuTinDung()
		{
			this._TaiKhoan = default(EntityRef<TaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTaiKhoan", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long IdTaiKhoan
		{
			get
			{
				return this._IdTaiKhoan;
			}
			set
			{
				if ((this._IdTaiKhoan != value))
				{
					if (this._TaiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._IdTaiKhoan = value;
					this.SendPropertyChanged("IdTaiKhoan");
					this.OnIdTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDuTK", DbType="Float")]
		public System.Nullable<double> SoDuTK
		{
			get
			{
				return this._SoDuTK;
			}
			set
			{
				if ((this._SoDuTK != value))
				{
					this.OnSoDuTKChanging(value);
					this.SendPropertyChanging();
					this._SoDuTK = value;
					this.SendPropertyChanged("SoDuTK");
					this.OnSoDuTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_SoDuTinDung", Storage="_TaiKhoan", ThisKey="IdTaiKhoan", OtherKey="IdTaiKhoan", IsForeignKey=true)]
		public TaiKhoan TaiKhoan
		{
			get
			{
				return this._TaiKhoan.Entity;
			}
			set
			{
				TaiKhoan previousValue = this._TaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._TaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TaiKhoan.Entity = null;
						previousValue.SoDuTinDung = null;
					}
					this._TaiKhoan.Entity = value;
					if ((value != null))
					{
						value.SoDuTinDung = this;
						this._IdTaiKhoan = value.IdTaiKhoan;
					}
					else
					{
						this._IdTaiKhoan = default(long);
					}
					this.SendPropertyChanged("TaiKhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _IdTaiKhoan;
		
		private int _MaKhachHang;
		
		private string _LoaiTaiKhoan;
		
		private string _TenTaiKhoan;
		
		private string _TienTe;
		
		private string _TieuDeTK;
		
		private string _TieuDeNgan;
		
		private string _NhanVienLV;
		
		private string _PhiMa;
		
		private string _Matkhau;
		
		private EntitySet<ChiTietGD> _ChiTietGDs;
		
		private EntitySet<ChiTietGD> _ChiTietGDs1;
		
		private EntityRef<SoDuTinDung> _SoDuTinDung;
		
		private EntityRef<KhachHangCaNhan> _KhachHangCaNhan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdTaiKhoanChanging(long value);
    partial void OnIdTaiKhoanChanged();
    partial void OnMaKhachHangChanging(int value);
    partial void OnMaKhachHangChanged();
    partial void OnLoaiTaiKhoanChanging(string value);
    partial void OnLoaiTaiKhoanChanged();
    partial void OnTenTaiKhoanChanging(string value);
    partial void OnTenTaiKhoanChanged();
    partial void OnTienTeChanging(string value);
    partial void OnTienTeChanged();
    partial void OnTieuDeTKChanging(string value);
    partial void OnTieuDeTKChanged();
    partial void OnTieuDeNganChanging(string value);
    partial void OnTieuDeNganChanged();
    partial void OnNhanVienLVChanging(string value);
    partial void OnNhanVienLVChanged();
    partial void OnPhiMaChanging(string value);
    partial void OnPhiMaChanged();
    partial void OnMatkhauChanging(string value);
    partial void OnMatkhauChanged();
    #endregion
		
		public TaiKhoan()
		{
			this._ChiTietGDs = new EntitySet<ChiTietGD>(new Action<ChiTietGD>(this.attach_ChiTietGDs), new Action<ChiTietGD>(this.detach_ChiTietGDs));
			this._ChiTietGDs1 = new EntitySet<ChiTietGD>(new Action<ChiTietGD>(this.attach_ChiTietGDs1), new Action<ChiTietGD>(this.detach_ChiTietGDs1));
			this._SoDuTinDung = default(EntityRef<SoDuTinDung>);
			this._KhachHangCaNhan = default(EntityRef<KhachHangCaNhan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTaiKhoan", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long IdTaiKhoan
		{
			get
			{
				return this._IdTaiKhoan;
			}
			set
			{
				if ((this._IdTaiKhoan != value))
				{
					this.OnIdTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._IdTaiKhoan = value;
					this.SendPropertyChanged("IdTaiKhoan");
					this.OnIdTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", DbType="Int NOT NULL")]
		public int MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					if (this._KhachHangCaNhan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiTaiKhoan", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string LoaiTaiKhoan
		{
			get
			{
				return this._LoaiTaiKhoan;
			}
			set
			{
				if ((this._LoaiTaiKhoan != value))
				{
					this.OnLoaiTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._LoaiTaiKhoan = value;
					this.SendPropertyChanged("LoaiTaiKhoan");
					this.OnLoaiTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTaiKhoan", DbType="NVarChar(255)")]
		public string TenTaiKhoan
		{
			get
			{
				return this._TenTaiKhoan;
			}
			set
			{
				if ((this._TenTaiKhoan != value))
				{
					this.OnTenTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TenTaiKhoan = value;
					this.SendPropertyChanged("TenTaiKhoan");
					this.OnTenTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienTe", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TienTe
		{
			get
			{
				return this._TienTe;
			}
			set
			{
				if ((this._TienTe != value))
				{
					this.OnTienTeChanging(value);
					this.SendPropertyChanging();
					this._TienTe = value;
					this.SendPropertyChanged("TienTe");
					this.OnTienTeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDeTK", DbType="NVarChar(255)")]
		public string TieuDeTK
		{
			get
			{
				return this._TieuDeTK;
			}
			set
			{
				if ((this._TieuDeTK != value))
				{
					this.OnTieuDeTKChanging(value);
					this.SendPropertyChanging();
					this._TieuDeTK = value;
					this.SendPropertyChanged("TieuDeTK");
					this.OnTieuDeTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDeNgan", DbType="NVarChar(50)")]
		public string TieuDeNgan
		{
			get
			{
				return this._TieuDeNgan;
			}
			set
			{
				if ((this._TieuDeNgan != value))
				{
					this.OnTieuDeNganChanging(value);
					this.SendPropertyChanging();
					this._TieuDeNgan = value;
					this.SendPropertyChanged("TieuDeNgan");
					this.OnTieuDeNganChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhanVienLV", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NhanVienLV
		{
			get
			{
				return this._NhanVienLV;
			}
			set
			{
				if ((this._NhanVienLV != value))
				{
					this.OnNhanVienLVChanging(value);
					this.SendPropertyChanging();
					this._NhanVienLV = value;
					this.SendPropertyChanged("NhanVienLV");
					this.OnNhanVienLVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhiMa", DbType="NVarChar(255)")]
		public string PhiMa
		{
			get
			{
				return this._PhiMa;
			}
			set
			{
				if ((this._PhiMa != value))
				{
					this.OnPhiMaChanging(value);
					this.SendPropertyChanging();
					this._PhiMa = value;
					this.SendPropertyChanged("PhiMa");
					this.OnPhiMaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matkhau", DbType="Char(255) NOT NULL", CanBeNull=false)]
		public string Matkhau
		{
			get
			{
				return this._Matkhau;
			}
			set
			{
				if ((this._Matkhau != value))
				{
					this.OnMatkhauChanging(value);
					this.SendPropertyChanging();
					this._Matkhau = value;
					this.SendPropertyChanged("Matkhau");
					this.OnMatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_ChiTietGD", Storage="_ChiTietGDs", ThisKey="IdTaiKhoan", OtherKey="SoTKNguoiChuyen")]
		public EntitySet<ChiTietGD> ChiTietGDs
		{
			get
			{
				return this._ChiTietGDs;
			}
			set
			{
				this._ChiTietGDs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_ChiTietGD1", Storage="_ChiTietGDs1", ThisKey="IdTaiKhoan", OtherKey="SoTKNguoiNhan")]
		public EntitySet<ChiTietGD> ChiTietGDs1
		{
			get
			{
				return this._ChiTietGDs1;
			}
			set
			{
				this._ChiTietGDs1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_SoDuTinDung", Storage="_SoDuTinDung", ThisKey="IdTaiKhoan", OtherKey="IdTaiKhoan", IsUnique=true, IsForeignKey=false)]
		public SoDuTinDung SoDuTinDung
		{
			get
			{
				return this._SoDuTinDung.Entity;
			}
			set
			{
				SoDuTinDung previousValue = this._SoDuTinDung.Entity;
				if (((previousValue != value) 
							|| (this._SoDuTinDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SoDuTinDung.Entity = null;
						previousValue.TaiKhoan = null;
					}
					this._SoDuTinDung.Entity = value;
					if ((value != null))
					{
						value.TaiKhoan = this;
					}
					this.SendPropertyChanged("SoDuTinDung");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHangCaNhan_TaiKhoan", Storage="_KhachHangCaNhan", ThisKey="MaKhachHang", OtherKey="IdKhachHangCN", IsForeignKey=true)]
		public KhachHangCaNhan KhachHangCaNhan
		{
			get
			{
				return this._KhachHangCaNhan.Entity;
			}
			set
			{
				KhachHangCaNhan previousValue = this._KhachHangCaNhan.Entity;
				if (((previousValue != value) 
							|| (this._KhachHangCaNhan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHangCaNhan.Entity = null;
						previousValue.TaiKhoans.Remove(this);
					}
					this._KhachHangCaNhan.Entity = value;
					if ((value != null))
					{
						value.TaiKhoans.Add(this);
						this._MaKhachHang = value.IdKhachHangCN;
					}
					else
					{
						this._MaKhachHang = default(int);
					}
					this.SendPropertyChanged("KhachHangCaNhan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietGDs(ChiTietGD entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoan = this;
		}
		
		private void detach_ChiTietGDs(ChiTietGD entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoan = null;
		}
		
		private void attach_ChiTietGDs1(ChiTietGD entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoan1 = this;
		}
		
		private void detach_ChiTietGDs1(ChiTietGD entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoan1 = null;
		}
	}
}
#pragma warning restore 1591
